### ISSUE TITLE
Wallet Overview Screen UX

### ISSUE THREAD

**Issue by ShadyIIV** [walleth/walleth#22]
I collected some UX issues that new users struggle with: 

- Send and receive arrows are not clear enough without text
- Transactions: It is not clear which transaction is a "receive" and which is a "send". User has to use the app for a while to understand.
- Unconfirmed transactions show as if they were confirmed. (I can make a transaction with 0 ETH fee, and it looks like it worked).  
- Camera FAB (= QR scanning) is not clear to new users. I see that other apps use camera icons, but usually with text (e.g. scan voucher code). 
 
Here's a mockup of the proposed changes including some suggested updates to the information hierarchy and design: 
![Mockup](https://cloud.githubusercontent.com/assets/1645834/26752178/66c73904-484a-11e7-88ef-064d86ea9d80.png)

**Comment by ligi** [comment]
I agree with some of your points - but disagree with others. So I have to close this issue - but will open follow-up ones. I think the 2 row layout has advantages - will talk about them a bit more in a talk I give at the ethereum office at the 15th this month.
Sure pending transactions have to be marked clearly (opened #23 for this) - I will think about labeling send and receive rows initially and remove it after a while ( #24 ) - but will also try to make measurements first if people really do not get it. I thought the arrows pointing to and from the value really make this clear ..-)
One question: did you do not understand it or do you think people will not understand it?

**Comment by ShadyIIV** [comment]
Thank you for the fast response!  

You already did a great job with.  You were asking for feedback on reddit, so I'm giving feedback to improve the usability and visuals to make it more accessible to users (which benefits everyone in the community). 

I think it would be good to leave the issue open, so others can see it and share their opinion.

> One question: did you do not understand it or do you think people will not understand it?

I tested these things with people that are new to Ethereum, but of course not new to wallet or payment apps. These are also all proven patterns and common problems. Everything should be clear when you look at it.

I did extensive research to learn about the different patterns and additionally found issues that users have through research in Github issues and reddit, etc. of other apps. So users of other apps submitted many of these problems, and many of them have been fixed and designs made to avoid them.

**Comment by ligi** [comment]
Thanks for your feedback! 
Might I ask how you tested these things with people? Did you give them the app pre-populated (e.g. on your phone) or as an empty app in the beginning? I can see that the MainActivity might look confusing if you get it pre-populated - but if you travel a common user story from empty over the first incoming transaction to the first outgoing transaction - I think people should get it. I am very open to suggestions but also have some strong opinion on some things - also have some experience in this area ( see my apps PassAndroid and SurvivalManaual ) that are downloaded by millions and used by hundreds of thousands each month. I often get feedback that these apps are easy to use.
The reason why I closed this issue: I want the issues to be atomic and closeable (ideally by a commit/PR) - otherwise I end up with a pile of issues I am not able to close anymore ;-) So I extracted actionable issues from this one that I am able to close.
Also this issue is linked from the new ones - so it should be able to discover them even though it is closed. Really hope closing it does not discourage you from giving feedback - but I need some issue-hygiene to not drown in them ;-)

**Comment by ShadyIIV** [comment]
I already know your apps, I even watched a talk on your site so I know about your skills and motivation. Design is a process and this is the alpha without a lot of feedback. I also have experience in this area and worked on apps with plenty of downloads (for example car2go) and did the competitor analysis, sketches and wireframes with another UX designer. There will be always be things to improve. 
 
Yes, when testing the app things get clearer if you use the app and users can learn these things (even if it's confusing and labels are missing - by using the app most can understand it), but that already is a problem. It should be clear and intuitive form the first moment. If you start the app, there's even text that explains the arrows. This shouldn't be necessary.

There will also be users that don't use the app daily. The approach is: "Don't make me think".

**Comment by ligi** [comment]
You are right and we have the same goals here: reduce the cognitive load of users
You are also right with Design is a process and there will always be things to improve.
But I disagree a bit with the proposed change to the MainScreen - I even think your design needs more cognitive load for users that never have touched a wallet app ..-)
Sure to people that used another wallet app your design is more intuitive as it walks the same path - but I want an app that also has low load for the unbanked and even uneducated.
But le'ts just try things out - as I said I am happy about feedback and will incorporate things when I feel that they make sense or I have the data to convince me when my gut tells me otherwise.

**Comment by ShadyIIV** [comment]
Agree, having data settle this is always the best way to settle design discussions. Would be good to collect more user feedback and more testing with community members about this. The community knows best.
