### ISSUE TITLE
manager.balance.io / WalletConnect / Walleth

### ISSUE THREAD

**Issue by digitaldonkey** [walleth/walleth#287]
Problem description: 
On https://manager.balance.io I could use walletConnect with Walleth to connect.
Currently Walleth app crashes (on my Android 7.1.1) after scanning the QR code.

Who to blame :)
A short follow up on the walletConnect discussion. 
There are basically 3 places to submit this issue, but the actually crashing app is WallEth. 

@pedrouid ?

**Comment by ligi** [comment]
Thanks for letting me know - unfortunately this is my bug that I introduced when implementing support for ERC-1328 - was tracked at  #283 and fixed with  42d94ab - I just did not roll it out yet. Did not see the urge as I hoped balance manager updates to the new flow soon and there is no real use case there yet apart from testing as far as I see. Will roll out a version now soon. Thanks for the feedback.
